apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-shared
  labels:
    flux.local/enabled: "true"
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/shared
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
