apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress-external
spec:
  interval: 30m
  releaseName: nginx-ingress-external
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: nginx-ingress-external
    controller:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - ross
                      - monica
      ingressClassResource:
        controllerValue: k8s.io/ingress-nginx-external
        name: nginx-external
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      service:
        annotations:
          kube-vip.io/forwardUPNP: true
        externalTrafficPolicy: Local
