apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jellyseerr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  data:
    - remoteRef:
        key: jellyseerr
        property: api-key
      secretKey: JELLYSEERR_API_KEY
  target:
    name: jellyseerr
