apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  data:
    - remoteRef:
        key: prowlarr
        property: api-key
      secretKey: PROWLARR__AUTH__APIKEY
  target:
    name: prowlarr
