apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: valkey
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  data:
    - remoteRef:
        key: valkey
        property: password
      secretKey: VALKEY_PASSWORD
  target:
    name: valkey
