apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: valkey
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: longhorn
      namespace: longhorn
  values:
    controllers:
      valkey:
        containers:
          app:
            image:
              repository: docker.io/valkey/valkey
              tag: 9.1.2-alpine@sha256:48332870af354a799964c0012ae1194a0bf2bf894eb508f945810596dc2d8d11
            args:
              - --requirepass
              - $(VALKEY_PASSWORD)
            envFrom:
              - secretRef:
                  name: valkey
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: valkey
        ports:
          valkey:
            port: 6379
    persistence:
      data:
        existingClaim: valkey-data
        globalMounts:
          - path: /data
