apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: private-infrastructure-github-deploy-key
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  data:
    - remoteRef:
        key: private-infrastructure-deploy-key
        property: private-key
      secretKey: identity
    - remoteRef:
        key: private-infrastructure-deploy-key
        property: public-key
      secretKey: identity.pub
    - remoteRef:
        key: private-infrastructure-deploy-key
        property: known-hosts
      secretKey: known_hosts
  target:
    name: private-infrastructure-github-deploy-key
