apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: home-infrastructure-private
  namespace: flux-system
spec:
  url: ssh://git@github.com/denniseffing/home-infrastructure-private.git
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: private-infrastructure-github-deploy-key
