apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: 1password
spec:
  interval: 24h
  releaseName: 1password
  chart:
    spec:
      chart: connect
      version: 1.17.0
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: flux-system
  dependsOn:
    - name: kube-prometheus-stack-crds
      namespace: monitoring
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    connect:
      credentialsName: 1password-connect
      credentialsKey: credentials
      serviceType: ClusterIP
    operator:
      create: true
      token:
        name: 1password-connect
        key: token
    serviceMonitor:
      enabled: true
