apiVersion: apps/v1
kind: Deployment
metadata:
  name: jdownloader
  labels: &labels
    app.kubernetes.io/name: jdownloader
spec:
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      containers:
        - name: jdownloader
          image: jlesage/jdownloader-2:v25.02.1
          ports:
            - containerPort: 5800
              name: http
              protocol: TCP
          env:
            - name: USER_ID
              value: "1000"
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /data/storage-1
              name: storage-1
            - mountPath: /data/storage-2
              name: storage-2
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
      tolerations:
        - key: nas
          operator: Equal
          value: "true"
          effect: NoSchedule
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jdownloader-config
        - name: storage-1
          hostPath:
            path: /mnt/storage-1/plex
        - name: storage-2
          hostPath:
            path: /mnt/storage-1/plex
  selector:
    matchLabels:
      <<: *labels
