apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app oauth2-proxy
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: onepassword
  path: ./kubernetes/main/infrastructure/nginx-ingress/oauth2-proxy/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: nginx-ingress
  wait: false
  interval: 30m
  timeout: 5m
