apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pe-weber-smtp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  data:
    - remoteRef:
        key: pe-weber-smtp
        property: host
      secretKey: SMTP_HOST
    - remoteRef:
        key: pe-weber-smtp
        property: port
      secretKey: SMTP_PORT
    - remoteRef:
        key: pe-weber-smtp
        property: username
      secretKey: SMTP_USER
    - remoteRef:
        key: pe-weber-smtp
        property: password
      secretKey: SMTP_PASS
    - remoteRef:
        key: pe-weber-smtp
        property: to-email
      secretKey: CONTACT_TO_EMAIL
  target:
    name: pe-weber-smtp
