apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sabnzbd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  data:
    - remoteRef:
        key: sabnzbd
        property: api-key
      secretKey: SABNZBD__API_KEY
    - remoteRef:
        key: sabnzbd
        property: api-key
      secretKey: SABNZBD__NZB_KEY
  target:
    name: sabnzbd
