apiVersion: v1
kind: ServiceAccount
metadata:
  name: home-infrastructure-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: home-infrastructure-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: home-infrastructure-runner
    namespace: github-actions-runner
