apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-mcp-service-account
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  data:
    - remoteRef:
        key: grafana-mcp-server
        property: service-account-token
      secretKey: token
  target:
    name: grafana-mcp-service-account
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-mcp-api-key-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  data:
    - remoteRef:
        key: grafana-mcp-server
        property: api-key
      secretKey: grafana-mcp
  target:
    name: grafana-mcp-api-key-auth
