instance:
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  sync:
    kind: GitRepository
    url: "ssh://git@github.com/denniseffing/home-infrastructure.git"
    pullSecret: github-deploy-key
    ref: "refs/heads/main"
    path: kubernetes/main/cluster
  kustomize:
    patches:
      - patch: |
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --requeue-dependency=5s
        target:
          kind: Deployment
          name: "(kustomize-controller|helm-controller|source-controller)"
