apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.external-secrets.svc.cluster.local
      vaults:
        "Home Cluster": 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect
            key: token
            namespace: external-secrets
