cainjector:
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      memory: 128Mi

crds:
  enabled: true

prometheus:
  servicemonitor:
    enabled: true

resources:
  requests:
    cpu: 10m
    memory: 80Mi
  limits:
    memory: 80Mi

webhook:
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      memory: 50Mi
