apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress-internal
spec:
  interval: 30m
  releaseName: nginx-ingress-internal
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  dependsOn:
    - name: kube-prometheus-stack-crds
      namespace: monitoring
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: nginx-ingress-internal
    controller:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - ross
                      - monica
      config:
        force-ssl-redirect: "true"
        whitelist-source-range: 192.168.0.0/16
      extraArgs:
        default-ssl-certificate: nginx-ingress/denniseffing-de-tls
      ingressClassResource:
        controllerValue: k8s.io/ingress-nginx-internal
        default: true
        name: nginx-internal
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      service:
        annotations:
          kube-vip.io/forwardUPNP: false
        externalTrafficPolicy: Local
      watchIngressWithoutClass: true
