apiVersion: v1
kind: Namespace
metadata:
  name: internal-dns
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gateway
  namespace: internal-dns
spec:
  interval: 24h
  chart:
    spec:
      chart: k8s-gateway
      version: 2.*
      sourceRef:
        kind: HelmRepository
        name: k8s-gateway
        namespace: flux-system
  values:
    domain: internal.denniseffing.de
    watchedResources:
      - Ingress
