apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-ovh
spec:
  interval: 30m
  releaseName: cert-manager-webhook-ovh
  chart:
    spec:
      chart: cert-manager-webhook-ovh
      version: 0.7.6
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-ovh
        namespace: flux-system
  dependsOn:
    - name: cert-manager
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    configVersion: 0.0.1
    groupName: acme.denniseffing.de
    image:
      repository: ghcr.io/aureq/cert-manager-webhook-ovh
      tag: 0.7.6
    resources:
      requests:
        cpu: 110m
        memory: 80Mi
      limits:
        memory: 80Mi
