apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: 0.20.1
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: onepassword
      namespace: external-secrets
    - name: kube-prometheus-stack-crds
      namespace: monitoring
  values:
    installCRDs: true
    replicaCount: 1
    leaderElect: true
    image:
      repository: ghcr.io/external-secrets/external-secrets
    certController:
      image:
        repository: ghcr.io/external-secrets/external-secrets
      resources:
        requests:
          cpu: 11m
          memory: 180Mi
        limits:
          memory: 180Mi
      serviceMonitor:
        enabled: true
        interval: 1m
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        memory: 128Mi
    serviceMonitor:
      enabled: true
      interval: 1m
    webhook:
      image:
        repository: ghcr.io/external-secrets/external-secrets
      resources:
        requests:
          cpu: 10m
          memory: 80Mi
        limits:
          memory: 80Mi
      serviceMonitor:
        enabled: true
        interval: 1m
