apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dawarich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  data:
    - remoteRef:
        key: dawarich
        property: secret-key-base
      secretKey: secret_key_base
    - remoteRef:
        key: valkey
        property: password
      secretKey: valkey_password
    - remoteRef:
        key: chibigeo
        property: api-key
      secretKey: chibigeo_api_key
  target:
    name: dawarich
    template:
      data:
        SECRET_KEY_BASE: "{{ .secret_key_base }}"
        PHOTON_API_KEY: "{{ .chibigeo_api_key }}"
        REDIS_URL: "redis://:{{ .valkey_password | urlquery }}@valkey.default.svc.cluster.local:6379"
