apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actions-runner-controller
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  data:
    - remoteRef:
        key: github-actions-runner
        property: app-id
      secretKey: ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID
    - remoteRef:
        key: github-actions-runner
        property: app-private-key
      secretKey: ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY
    - remoteRef:
        key: github-actions-runner
        property: installation-id
      secretKey: ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID
  target:
    name: actions-runner-controller-secret
