apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-mcp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  data:
    - remoteRef:
        key: home-assistant-mcp-server
        property: home-assistant-token
      secretKey: HOMEASSISTANT_TOKEN
  target:
    name: home-assistant-mcp
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-mcp-api-key-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  data:
    - remoteRef:
        key: home-assistant-mcp-server
        property: api-key
      secretKey: home-assistant-mcp
  target:
    name: home-assistant-mcp-api-key-auth
