apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aws-trust-anchor
  namespace: aws
spec:
  isCA: true
  commonName: home-aws-trust-anchor
  secretName: aws-trust-anchor-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: aws-trust-anchor
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: aws-trusted-issuer
  namespace: aws
spec:
  ca:
    secretName: aws-trust-anchor-cert
