apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
spec:
  interval: 24h
  releaseName: oauth2-proxy
  chart:
    spec:
      chart: oauth2-proxy
      version: 7.12.12
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
  dependsOn:
    - name: kube-prometheus-stack-crds
      namespace: monitoring
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    extraEnv:
      - name: OAUTH2_PROXY_PROVIDER
        value: github
      - name: OAUTH2_PROXY_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: oauth2-proxy-oauth-app
            key: client_id
      - name: OAUTH2_PROXY_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: oauth2-proxy-oauth-app
            key: client_secret
      - name: OAUTH2_PROXY_WHITELIST_DOMAINS
        value: .denniseffing.de
      - name: OAUTH2_PROXY_COOKIE_DOMAINS
        value: .denniseffing.de
      - name: OAUTH2_PROXY_COOKIE_SECRET
        valueFrom:
          secretKeyRef:
            name: oauth2-proxy-oauth-app
            key: cookie_secret
      - name: OAUTH2_PROXY_GITHUB_USERS
        value: denniseffing,feltenj
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      className: nginx-internal
      hosts:
        - oauth2-proxy.internal.denniseffing.de
    metrics:
      serviceMonitor:
        enabled: true
