apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app metube
  labels:
    flux.local/enabled: "true"
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
      app.kubernetes.io/instance: *app
  dependsOn:
    - name: longhorn
  path: ./kubernetes/main/apps/default/metube/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: false
  interval: 30m
  timeout: 5m
