apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant-openthread-br
  labels: &labels
    app.kubernetes.io/name: home-assistant-openthread-br
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      containers:
        - name: openthread-br
          image: ghcr.io/ownbee/hass-otbr-docker:latest
          imagePullPolicy: Always
          env:
            - name: DEVICE
              value: "/dev/serial/by-id/usb-Nabu_Casa_ZBT-2_E072A1FB75C4-if00"
            - name: BAUDRATE
              value: "460800"
            - name: FLOW_CONTROL
              value: "0"
            - name: AUTOFLASH_FIRMWARE
              value: "0"
            - name: OTBR_LOG_LEVEL
              value: "notice"
            - name: OTBR_REST_PORT
              value: "8081"
            - name: OTBR_WEB_PORT
              value: "8080"
            - name: OTBR_WEB
              value: "1"
            - name: BACKBONE_IF
              value: "eth0"
            - name: FIREWALL
              value: "1"
          ports:
            - name: http-web
              containerPort: 8080
            - name: http-rest
              containerPort: 8081
          resources:
            limits:
              squat.ai/zbt-2: "1"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
          volumeMounts:
            - name: bluetooth
              mountPath: /var/run/dbus
            - name: data
              mountPath: /data
            - name: net-tun
              mountPath: /dev/net/tun
      hostNetwork: true
      volumes:
        - name: bluetooth
          hostPath:
            path: /var/run/dbus
        - name: data
          persistentVolumeClaim:
            claimName: home-assistant-openthread-br
        - name: net-tun
          hostPath:
            path: /dev/net/tun
