apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  data:
    - remoteRef:
        key: sonarr
        property: api-key
      secretKey: SONARR__AUTH__APIKEY
  target:
    name: sonarr
