apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ack-s3-controller
spec:
  interval: 30m
  releaseName: ack-s3-controller
  chart:
    spec:
      chart: "./helm"
      sourceRef:
        kind: GitRepository
        name: aws-controllers-fork
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: ack-s3-controller
            patch: |
              - op: add
                path: /spec/template/spec/containers/-
                value:
                  name: iam-roles-anywhere-sidecar
                  image: ghcr.io/denniseffing/aws-signing-helper:1.7.0
                  env:
                    - name: TRUST_ANCHOR_ARN
                      value: "arn:aws:rolesanywhere:eu-central-1:514266269969:trust-anchor/74a9e9cd-97a2-4b99-a51f-2c79109e8dc0"
                    - name: PROFILE_ARN
                      value: "arn:aws:rolesanywhere:eu-central-1:514266269969:profile/4cc63273-6c49-4499-b6e6-a879f644da30"
                    - name: ROLE_ARN
                      value: "arn:aws:iam::514266269969:role/roles-anywhere-role"
                  securityContext:
                    allowPrivilegeEscalation: false
                    privileged: false
                    readOnlyRootFilesystem: true
                    runAsNonRoot: true
                    runAsUser: 1000
                    runAsGroup: 1000
                  volumeMounts:
                    - name: "certificate"
                      mountPath: "/iamra"
                      readOnly: true
                  resources:
                    requests:
                      cpu: "10m"
                      memory: "16Mi"
                    limits:
                      cpu: "50m"
                      memory: "64Mi"
  values:
    fullnameOverride: ack-s3-controller
    aws:
      region: eu-central-1
    deployment:
      extraEnvVars:
        - name: AWS_EC2_METADATA_SERVICE_ENDPOINT
          value: "http://localhost:9911/"
      extraVolumes:
        - name: "certificate"
          csi:
            readOnly: true
            driver: csi.cert-manager.io
            volumeAttributes:
              csi.cert-manager.io/issuer-name: aws-trusted-issuer
              csi.cert-manager.io/issuer-group: cert-manager.io
              csi.cert-manager.io/common-name: "${SERVICE_ACCOUNT_NAME}.${POD_NAMESPACE}"
              csi.cert-manager.io/duration: 168h
              csi.cert-manager.io/renew-before: 24h
              csi.cert-manager.io/is-ca: "false"
              csi.cert-manager.io/key-usages: "client auth, server auth, digital signature"
              csi.cert-manager.io/fs-group: "1000"
    serviceAccount:
      create: true
      name: ack-s3-controller
