apiVersion: v1
kind: Namespace
metadata:
  name: 1password
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: 1password
  namespace: 1password
spec:
  interval: 24h
  url: https://1password.github.io/connect-helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: 1password
  namespace: 1password
spec:
  interval: 24h
  releaseName: 1password
  chart:
    spec:
      chart: connect
      version: 1.x
      sourceRef:
        kind: HelmRepository
        name: 1password
  values:
    connect:
      credentialsName: 1password-connect
      credentialsKey: credentials
      serviceType: ClusterIP
    operator:
      create: true
      token:
        name: 1password-connect
        key: token
  install:
    crds: CreateReplace
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: 1password-connect
  namespace: 1password
spec:
  encryptedData:
    credentials: AgDJ2cPZqJeh++ORHDX4sQMH6CHS2kSX9a7vE++LdYxu8QGbHVcRz0LgNH3PEodc+gHy2YvmVoScAB39FzctkLpRZxZNoVdys6lgt9b2JKo0kYihq+ZOd6h+VbpUGUNDOA3LiNidPZAJo/jWY+mYSbx03WKLUijiuKQFLHjFFdfvuhrDesKHnlIjmhmpDET/Kf57faHXRKLwPjHRnUPcsloblAKMnMgYK7XFFO+E80bOGyhns1Oqy9fhxgFmHwHxQSwn5YvZTnMbRTsGQwBIA9JcXcLHTp9ASuz3jY42ryYeKsw5J04eLUhsuu2hoDEKUhDzKejmHIA61bjMZnfr7uPg/AUGCzDT1qftyBHQ1ll2/Zq6gwLyyX+ycCBDf0N5EW+cOu5s7im99sifAk4CJDlNB3PxaRsCrHctApBrbHGL35xSTLnZUmhg0mK7dZX0I0fh08VCrY+AWZY/AGIP+qswNHoSL3M290PszZ7gODx1ezpvRJxhECcx8pIeKR/SA1KqRUM/LJzWEMSWCdV2743ELrQOFSsnyTACij65qLmAOdFX71tPRHQvZOI6SzMNsC06A+mrBb7amcaGDbXi78ARZa+s/ya43jm91fsYRwLPuCpvfaIxkGlguGSuQzwG942i+aPp5c+neiiTfyAAspP+4tly0+oRChAeXp81c2kEkd5SvYSD6ShljlY4b6GkZpBSJrvjVH/MnGDuV9kyeJ9ZDnGvSYmjbWvS1+833CV/tY9HZHME4S+kmDR8M4ch4XpTkHUCljR0AUc3QCr42VjofNLTMGrG69Vv6d5kHqDXP+IGC1QKgDeRyTOFQQmh0Mdj21/btE8k+Ozkwd2QIkAWfx55dgDKC0VObfvzSmpMgY7P9LRENhOZDTOD8HPvmiYrlK+kMUwm6wuHIhrD58ehTbSh8QhwDXulLOkUxXoUayq9gHiEHNk+un6sMywFd8tBTTQvqP2N0PnpvSEsUhaFg/Ey1SvDAmrk9tQ2BrnfDMV3T8TYHSUXcZVMKQLe8gFzehnKR0lpJIu9D1JIeKyJ2V2uMvXgyPF69YGJFUhLGt1O4IRviLD7cZ+kOzVBZ6udN2IP/Lj7E+5c9M2WpqJwGGbzJxfOhNsQsqDNq9/BKKH7YYqKvx4DqtYVuP1KNSmjUl+oE+ZpnHcMs3RTqWnH/P7ARh8weyaA75hZ6taFOT3X0PA8fhsIa86Ziw1+tesGGOtHAO82xeWHauQPt9TzFU4rrbvrD6xnbBgEkpjf/td0DDU09Rakf0w13eBOulSyaoEnesFlrhWbk4UR0IeX9nf02fFiVih1d1FPBCSU57LSKpt2UuAwE9SHQ8O208ZAFj1zPA8m+Sf2OsfxjnAbuKZhE6tCwsYsM48A6ZokEPAJ2Z6zNZDEmPEN7RdZ1UrxPzeWiqM7zRFdgcxt57QnwATMA4EazDCVsZDtiSbJxYfzMKsz+w81R0+yn78jk2ta2s69qEFaNbfT/E6jgH241m0cUmsWjgafJWuJuPtnlPbfM6gF/roAR0YmICI3zeVwhQLcmBHoN2uEFtC+j5rKiaYyXXpVfblrLyqFQSe5U1UuDNklBh6q6A8iTg0hXsd5UatwLzz9UpIj0fG1JB8eSqomKLo17o3ToA8KPPTi6KJ/lkN/GlE3TI7/8ZbHPhRdghbOrlSd8G2ScRktITwPlN/p4p640Dh6Bg0VTjsN7sRxOi9r6FuFWVtraG9Ew9PZIIDuLhXtY8A5gw+R/yllztZrmE43ZYFEqbKch7IqHs2Fl8Lev8YKn832wrPZR8JtIeAuyadY0KVGVJ0EbysLgYELSvjx8q32Zqj5cmgwgjrd05U2c5MmoBxS5CYH5E04jaSYo9w+DW84QC1BLB0Fg0wimdDF4NT0SLaXZAb+pQYBKsfZUogtpYzVUjdnpxXcoBx8Je+/1R/XGdY4FVMQtLL261FiMzbmfjwcn9neoPYvxymACLG/dAtNcFCR5KhTkBL/EueUie/bAQQmNLOqnaLScdbRGLHqBQiqViGKhzDMOlftqmcWrP1Yb5bFrO+zChkEjGV6RhG8fu8jsS72ZnARCNf4XO91RJK7cgHcf4zNGvdvg8pzlNPBufzkXeUZyrI2GrivNGV3ikY1jOT7MtroVJGZ36iP6/13/tI5PQSu4nPDo3WLl1m9HgrZ9qO6vC9B4ahhirrC1gv/GMmLVB0vwjG+ELQJCy9aN5Qb43I15abfCl4IbwQpIo3CWww30aqlJMQluSXZxC5+nwEGt9xMktavptO6sVGIiF9Ek5AZSG5obcKfKN3iKwoaE3m5HDFqNcj1pOd8Qu6LA47vSSrxHO29a1RQwIYZ5Oq9nXCMlPLYR/SbbnIJh6Ox936QzkddV4d8jl1zVX2DPZEkCxBWkgqvRMO0ne3kY3oDtMfpaqdmJShmGJepD0KnIMTOjLAsqu7QCDpch7AwLpfWBth79eJbLsERYZilDfER7F2foiGPiQI2bQ+QM9Rrdr2t/gT3Ah7CSsg+3/Ju3bwC9HZv/cWuqKr4r27PaBTanoV94TYLNsXfd+Dn4ABBc82BOksXv3xIiwis8n1skTc3Nm8c/EJYtmVEDAw+wKW12wOAFVbkBuguJXTVd4QHNcqMNAiKEi2Fu+g7FTz1QSMLGAg/oGQ2WeIuH57C1/NpvZ8dH9lyPosC385AeDdnybIgZtvFdA0SDUCNMg4=
    token: AgA3RBTmmxwvp+dsdHjIQRZeh8hq5wAbF7BR/J9dTLguyWI0q7wEj6RHSuC/n5+URIBiSNVAdJmXFn+s5tDS73nL/kEY0QepvIvBqVNDz/D8fP58raFHwT+3XRKWHoNCiFtJVwiLq55KnUPzRSPsaDIxY2ZN6Tk5UXPcAUq8we7QQSvXRomwSEwF0eidnBnbJly1Hr8xM0lSo8HZoS7zP3NJNhbFVmjeewB0RP28ctjsar+kuQGQTd+0BlD1BP8KjYUjUeioOZ/vsSdWfd20F52oxNM9NINV/BzIdyEG6Be4niRBxcoUFR3j4J8+W9UQ6CeUGMymsBoSbsxJYqqZuREWv45KIMAagOWWAMNr3pNY+3+QZ0HNz5cK5UqWD7AU7V2Hmm2nzApbZVT2Cd/JdY8oqH0spZm0lGNGoO951M6wnI24i95VWi6osfmHGm/I6HICLjxB+mEUJc8js1tXj59V8eww1+/jB3j4NOVtR7pOc1dvnj9Sns5PisGHA2ZLXm9SOQ9lOYTUnWpb5dQhE/N0daSmBAH1ywLYzoZbeJt6tNutkokq3s95JePgxzSfRt2r6el5rL5uNyqhzORnuMax5G9IRMC9cwiwiwca0i8Kov0Mb0Zze1djCw/5PTH3zkoVVg4FPxjQXUOb2WmMQU6tcf5L01ugvSl6YvJ7umwBiVD++uMdj+aQslYsSZZZnifLLOuHSI3pv5pnES4GMx3V93UG4tvWt+rjmFXYFbrZpOpagnrdWPFN9eTQXqQXnnwA9VUKmhgfua0zO0hybwANm5MPQmBFTEi9ffShGJSHAFobo9jHyC79VXUF9j22e+rsJtlQMB6CFx2WOys0NhicrXf+UWY9yaBUidZFW5L4oVSB9XN8d0t52xOv4SiUujttsPYg8W4aHnKAOSxIAY0COJ2WS55Il29KbpS8EJx1dJHHWMaEKN3r4DXAcD51wDDvNxigXfKs59C359mOUOmIgp6sk8TNRxXXoRz2yQjaXnA5qt67F+ZPuHldipl+LXmZ6LHGs47iEUYUJkBnVBzjKXBeVFsdc96T1PCW7My9hVDV1oXjdW7lqtPo5dUwM4Y49XyuqPqmhltdx4R2/rOXLUd1Z5Ly1Uz9d6ZpbgeAAvuowRmiCccDoddnTNTnw6anLQhEG5+xSYi3jeDy4IME+/LKLSnVLbzHvnnsxTLurGrIsXakAuYvZ41IRzb02oUCSHp8HH/YX26XIXGNKNiYeFrSRfOMMw4fJYbroP6TTP5Ew+NySq305CoWXcNZKHX12khfgkmWb15aegjPaJRMT+WkLNwwoNU3MvVyWH7NhjkezBOWq4hz/4CxGAhLB0U/3wl/vqgmTIhzjgFEpG0yPihh6m0tq0NZp+u6xOPYPko6Tv5sn7+4q5E0rCe+U644YRjnuaNDxnWGwossqhf2r/kIogXCjI0XWGGqUtNzqVkMtb0u7IRsZPzGP9GcM6yZoKxbwPKekMbxMeQBKylVp0EG2SOTS1ySbFLiU49MJJxd7en2OMkqSzvqG+3J2C5tveRCIPRBNL5z+G4K2tGlQjI=
  template:
    metadata:
      name: 1password-connect
      namespace: 1password
    type: Opaque
