apiVersion: v1
kind: Namespace
metadata:
  name: 1password
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: 1password
  namespace: 1password
spec:
  interval: 24h
  url: https://1password.github.io/connect-helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: 1password
  namespace: 1password
spec:
  interval: 24h
  releaseName: 1password
  chart:
    spec:
      chart: connect
      version: 1.x
      sourceRef:
        kind: HelmRepository
        name: 1password
  values:
    connect:
      credentialsName: 1password-connect
      credentialsKey: credentials
    operator:
      create: true
      token:
        name: 1password-connect
        key: token
  install:
    crds: CreateReplace
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: 1password-connect
  namespace: 1password
spec:
  encryptedData:
    credentials: AgAyTXq3Jo5TpPIpIPVnNS+TUV6o/HsTXyUkfWklBKONFz+V8E1B10gAHINVAhGtuUEFbJM95TNG51f50ZcGTWZTC9ZiHCCoTsy0dzPRNJV08Xg5Z/MofNx4YEfM3BTp7EnRFL4ftACWQ9nynqT3ZOucCQ9G3Kt0qg+Q9dtn9xtv+vvwspyFpG5Xzt+h/gHGM5dLZDsqOoeHOSMMC6wuQmuLHkTzXYtAHBi126nN8ujMoozREMvfOQiBsYm6blSt8RJdL169m53b5NU3Mzr9vJQb9eRME2VpPlCgbMzkVL7Qb3RggSNJ9JKsSaL2I6uMhbdNA+42aKpn06jZwFwtb1ZfSHxSwLLbYAsYBDVCjLP30aFcjpMCTvGuQYUB/ByZ/YX7VP+v4EACy/Ag8uwRVMUmGev8UGqnsFf/7WttP0Ym2nYjnGsf0FP8KEEcRxmyjBOx1eWERO/dSvZC8y8KxYm+1Zvq/gqokODGunghQH12PbNIHYhGFeyBB33rkx9Iw5JXsRTtkMMQ0oDY9xK1MlPbbJw6H0v0hPeln3I2I83YLrFZnye45FOMHO9Y+LpXKHPl3iTiOGS/GdTjXPNacg3zlWlOT6WTfTm5gK0d4U+TcKsYojFtkXZPDU2uMlNs765+5AelfDjoKruiOHWNADI652THuG1Hz9p4qKq4k9hxVSd/G7RQI5Cz8gawibBj9lzkhrZpGPkc4djmNLi7E4tc7d8x5opAeHCz1Q7pFvNng+MN9zSwMBr+c0+8cOJ8yLtWVm9uOSGIJDYhd7k0kCuDPLZRiSxDGF7HWN2Qi0fxzxN42JugxryZtWGgHalPdPF+VPhuxxIwned6tSBlKHHZZSnVKyjG1ocGHTbY7aQKETwfnwTvsuooZy13bKrZQarLHEiNrU5dTWNkVMm1wTeoLciMl/DQ4U0V5liAbLHYEmVHcSPJEMBoW3M42TgegxyokIaEd5T2UpB9rGBtfcngBJfj5LtfWt01RCIeGWMBMERYBebrbuQlRuuJGujK06gbXdg9FCfV5Xjm2D2M7HvgFugs44JF00jmYI1sqki/979hir8mzSLezWsa0ZoSgvbtyp3XAtV/0S24Ml8mGHzOJSQfR7Dn2iqsRiwb6eOzDHoHQwL6GX/ZjZWyC447dINS2+YozSglIrfJK4VKZMOQ7qaJ+c2ZFSdlty7cuc8BTxjxRvdGGsTs60GpAIWZl1S41xALe1jVbe7p/RH9B/1t9wwJ5g835EpZPyken+TeAKke4XmFs32SFkZe4teuztLjuyzv5sV7eBzbBsQxCHGCl+2Xt+Xh49bw53B+lRafKPV5OtOGdJLZ+goPQ0y0ofRba/slR+uZX5Z1fWSWimehryqWSJNlnNXmNi8AURIcbXHslnJNmcrrDe61vEJCXm+CqJtX6Z0wUTCEthPbogb/PSAsSIAgK/Pr03t7T04RAhTskWkzGihmKJRSC93KhywgFEpSx6LWq99ugEdsjFAAtrFvWzKnSMS1bopyBvCtyAGLZbvXrTLnxsurF7oTaCsQy7oQtpGI8vx2RY6wI3VN9X6VRuIE7YkZwifntasKqsKRzhhbG0UW25jSNJ622OnxAChjSNUrFMTIwPgfDV/Yi9kHXORrEjSsM2Lhd/tWLCvNcBRDdbU9zhisLGhBYsIX0dMZ2ZXxNn5Vnjj01C4g4MOB9D8bpVDL4omvlZbXlOx9r7Ek59xKOzGlQlDockKWNobcusMil5pmRh4XqyFNPFwqKmd6el0grzTep5354sXR4pywnC/IcbiQ+lkDrXaO82Wb2xQqO7B1gpLNucTL8D9cZ9mpQKa1YGuR3YqNr5k4/1ajgbetevI3ao1oBG7UqqpJB43HKWifR+SvxAv7mSo2PBpW3fwKiPaW14J3f+uMo6wfR1iwsh8muG9YIgkqTCK8Fmz5BPFTvdJRI/e+bYhsgPHw3HGmtPOxt48ryqebtxPZ7vkSVXGrnmOfclKWVluh82ucbg/BNT9+Hih5TN/MK+TMVzqTGGeg7t1cef1Q0JN6eg/RZPE+LrprWF58ZJRrtIcJ9fczJczg0LAiCgUdKfXYo5JPDHxDeTeQC27FaVVnWP+dahL7x0IhkaDIkvBEnRWbe0EBEZY9/RtesoVFQpDpbv4eiK41olxYXrvKZlJBIAPfcBCavJA/q/UYIMcXMwkMsfiz5A12HcROXR5viAS7/iO5sRYQIV4YRfjwcEsLOEPpKQBbibugld/l+9aR5L5mtMo62t0nLHepq8yh4EUghwDg0P5r89oThFknFpY6wY3Do791kI++lVCHV6bEcBO+vwIEfYQcGCJJEl0Ew2s2pqWyoSbbOE6UGGEO7YyASZSSgSRAkiqfkwam1cNQHJCnLkKaT1A6xDdY0yGXL1UxSkaJgGFaFid4ybVSdp1T8LYDs/2Krc5lqi4tXWkXjra3hMvq7/f/7+1HN28RUDO3Wekclfl+aJAb/XgMZeRXY6b740mhL5ubtq73vtTpi7sRiecFgSbx/HFM0aHOBeVZOak2YieT8SCq1EBPkeFL/tTXCwPVu5cM7Xp2jyzDhAwq7D6wqDRt3gX79P7fsmE3vu0rp1+e0EP9M5VmjfElpPck+JgUT/P7QP3LqQ/K0PzCQtNz+qIA93CQGc5W0VubXMk2NkBqhs6RTA2lEaOr3NNDzrBTIbGICxTATh4BxkalOffAx6jotJBg
    token: AgARmQOIK9ebmw8rg1tYJ1sCpbZ+LfCHUplemBO0SSSaLI1ea3QfgyzMd1Cq12StTpesAhRAcKsTS5EX4DUr52y5tmGpNs8nTrOe7FCd/vsaFj24hB1Uh0vbMJ2RKk2v2bNTMESdRqO8bHJYNlvmknK1PyGooDF3p9SBfmClat+0b+kfX7R0fuLsIHC221wB/jQe1xjZo5speDIEtyA+gmGVxCGiskOv9Ub9G6lmxAj04rsBLp5xgjbBA5V9lZ30Gv2HS++JvXrTMps0yrcV1Oa0jBxQuxFRT9NhLv1kcui0f+fVWoiL2MCD61eX/iS1JejUvwga+lc2p+i4qZ5Bh4IAeZh+Nbx+gB1mgv6dxInfAeODodBTkBudFjbLuDiCHcI2ZoDw4Gk+DYHvNit06L7qL67e+V8uzbmHGUZmU3lmntUS1ihSWM+npCkt/Tal4Jjg6/2ZjAYo6OhO+4dF8GWZoug4Oz3rTlrLBAtwsuShzIXPOSuJY49iFjYVdPYyuIhdU1IMrpHchW7TKYwRIkmveB+FgdSw3pwBnS774OWRDgSO2G9ZKw4rraQcWgexP1g6/yJ8Lgk2F6mnSr0IdNNbSV+YeMMEJ4oRHMa6s2NCsWzVXI+tG+LNZ4W4Vs/rqVO4xE1PRpIL+Xz0MlPgMTUf5ZStCVCXEcfdx8l5h0ck1VqN2Y0tIP6YMAHuN+5E52OvLRPy9VZPEN4XlCnCUUDpf3vTxU6LOqv/BbolrHqJLPUFHnWhpWcnzS542AnN5ij8ZNIuoFe3zYh4DoFWlBzK+kme3d6XWtAm30Bs5UlJ0NLmFN7PiTjuR5YN6sbEBk68AcR43ZmJwSm3HFoGh5uoo0+ljVmk351GN7w8neuQUdOIyCK5dCd3YOEZasxxm5oBi6TS6iOWkfL2GIHjK79VkFHQlw+eWJajE9stjw4DkguKkQjasBOC2/Tbc1PHN6e1LMFfA1GuVd3NpTf8a1D+ZhGPfA1C+Ryvw3XrB30Wlq61rjhteaDBOTyNtezfrsaDsQywKq5BME09dUR7K4+2Vx7rrqsSVVb3YkbQm0uzIUGNwOGyOL6k3I57fHAZKtRMRDpvcaoUnfrAHowMjvyT0ZzRIscIraJGZZrmC96/L/lnJrgce66UaLKuAGU2AEPcA2hgUfkJABgxj0pl/SYu3snMglxw6AqV3zz+vUieQpszOv32rH8QGG90bryQpE2d8MgRq6wlQRUwrKmmfEReWHpbDZ1EKs7c6+Txq6kT5RBHfIKH+6E5IPmewfmPB2vxbS7ty873jTSzJW8dGtALc6MTNideI7TmmzBtwkHErSpv+G6zbmLGySxfZDd4F0gSwMrPWlbaApCsEvobMvhWSulMravLFvvYcKzZDq+ZZVbitZKHNvTHnbs3h+q08d+nLm89gi4adBWxbVY8FKrpbshRpTwLawpg3v8TUVDC6pLd+M3Ybp5ILYtkxDABAk/MAOY0WWzs9m4urPTA68lYfvO4y1AE/VWlu8k+/HyiIPHM1JbWX4EycmFHWzLtsZRjjLVPrRNrPd8t/2qcoglN2U0=
  template:
    metadata:
      name: 1password-connect
      namespace: 1password
    type: Opaque
