apiVersion: v1
kind: Namespace
metadata:
  name: 1password
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: 1password
  namespace: 1password
spec:
  interval: 24h
  url: https://1password.github.io/connect-helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: 1password
  namespace: 1password
spec:
  interval: 24h
  releaseName: 1password
  chart:
    spec:
      chart: connect
      version: 1.x
      sourceRef:
        kind: HelmRepository
        name: 1password
  values:
    connect:
      credentialsName: 1password-connect
      credentialsKey: credentials
    operator:
      create: true
      token:
        name: 1password-connect
        key: token
  install:
    crds: CreateReplace
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: 1password-connect
  namespace: 1password
spec:
  encryptedData:
    credentials: AgCqpgVx/RfoakHQQ+5iI9kH6hW9EzVLF915sbr1yPgVjBRNUBQIshIuGQYxnu0Gow9RDAoh4RNJhRL6zo9eUh2tO2NGVvxfGETF/lXk2mfRuyT5D8zozUusZQ3yH+CPsySacQOhNHzOXpvLZbXps/WUZgjbEVs6+WYumm3s9HmAy8yB7W4xVP+QbC6RbaW5R2LtsTp0qe+j9/6aLZVKIZIPjVHa+vooY2w3hoo9SMpPeuhcUIe6UAhCAyRNK0/6MXeP5a5faI16N+v7B7oVESqtvM5k9TNqdPAOcqVUhDeR/FWObCaAHAtI92OedLMO1decs92IT+sEOpgGAjG3pf/ndCcYRf1/jg2rXSc10jgjyhEZOeLy6w0UcfEw4SwVQNdUCpCSQvVa19IApIZPTALz6NeX/bkINSQejkUY7rTbmDScb/JwVAhjbliCz7aotlTZnWkPMzfcw0zD9g6ZMX5hCjF3kAixhi+gZerni1lndBzuICZdeQ0fJmF+8W8JZHtwcTEQxP1z+ErCWkTKDMhozQvCkLpg2G88hbOQy8Zq2HQyozWHVv3sak7I3q9CuJRkdcqCl0QBDnuETyRAZRV+mS7CZG2PKAeD4BevNNNzd0J2WpU69bLu+crD1fOWdJTpJfRa9l1q1oa8+sBGMghIw50rZM8aryboFpPZlqFIoTNDsbjCOeh4S9ReNQ78L2+KKHPVCicwKYWOsfEuHq6d5QZEqUdp1bm9V9FSZoPicqN6Ij63VjIen9j6parAKF5l4q+1tQQ9UpyJ1c3402hLQpVGPjfan7CKi0mxGn6m5g5GqNKuXLeFShumjorr+V4MMHgcnw5ijf3AB8DmVXVSjotocGefjdc0mxVrwz9s/IiwOQVoRCviqLpixedkV1EdmWUDVJ8j/HwPqiXWMfumb6sndN9ieavSn8PQMKhxu4ope45DH45MAA2/+uXEa+rMJ857C8LSP0eauMa5aRDf7CbCSBfk5QzD63QJwb+CNQA8qiekF/+58WmnHWlJcXMrVk6y+PNxk4HgHNKFyEm/RDTtoCyd8uD3emlPqVm6W8JFB/DzPPenQPs3iCZOObjWxS9OSGB4+QRRRyLh2qx/hpCB6yy+pO6EubWL6pe0BcsYDqljntxcxeLwTepy4TZ5cMWE9KRqKeaaa6OkoMajXNU0QYEXpWo8AfCHxx3IsfBKAlkUDjk7YTwPBnZGSi2vmN90IMddGiAwgjxwB56e8+u/m9PKEXxIKj7hFP7XC6XVMr7PlihvHQ8Oo/0ICcExQ6VDaPD0tb8Uwo7QjRanE0gmNdoaJ4GtxnfZOcS8yN8g0FQe5Pz5PBl5+oTmUO7efNZIHBOJusqDg1amM8ORs/pnLrdD/U6FY0SZNiYePnDRSETOjQS7OOGLdgAmJzAd29GXfvq95E3ciKqBlgvWAhDyR4NVzXZVENT1rT8hdXcu/YldljsWNNyuzUkeXHl21Apr9/v51Dexd7CJJ8CKjv2vItFQly1AA8qv1YWWjVm9LYOjWpWG+xDrys500/Hxc2Sb46nhn08/gA+x+p0yrJmMqZtPE2MMh0rrYICmfyx11mY2lh7QOHCG1Rl8f/KfBQyM5L8EGMWdYc3Cf5sutbZFOFXN7y+C7lsgdqkjc0XyHee+0LSDnQ87pFtsjndK5ciACQ/Re5Qp7Z/dy8dKbisazvABN/WIBatSsScE7oJsMECdKiEM94zbjYqEE0+fiZtlJT7h4cWXdcWwFog2a9C8esg6uHfy4doauf2SpN0hJm0aNDqOiX6xoJTzItQEuoOLHN0Lp21yd3tSP2jk2hKYA9vTvOhTliFcEfWySl3AzBvjY31a/GhQzomQ6G/Q0pELcUtKPxMvUIIKa348TsD/2MHhqjeBSn/M15R73AxCCnxvhoqBrUNMGbKKlnZIJ2m3ZE9LPccIVi0gGrpSgSaJPi5aGHSI7psyE8TVSUYgnnijOgYAzgZziggiK0M1L56eYOVitl6k5GAXYShnhWFNXpJezRekGKvjyZrpYriQwpHp91O40Xuv5UHQFmp8Q2ig2WXQgRmqxew78uxZHL0vLkEKzlKZ5wkMBkV2KWZ5Q7P3oZ97/dVv1FX6Brqoazsgg/SfWNToDtje+fRtHbA9VSSdWDW2tUo9IRunUhA9qfMeqUycYGObxlTVhE+qPT4xcejxpfPVpooR8BtM+Kq0/fo8bFn2Vr/KxypdZSS9U5ar0yDz8oKpWaKrMxXQgBk247DcGhMPCmXbL4YjO6Cbwsp/6FRz1LvmAqI1xWgISqaUa1p1NBzovwmkFW1LMSU8d48DfYWTYWQ8zR1e9VniP3qj7A45HxF4VJNOxNNRIF7KEaAIxz9nfxWr7k21VBFj+NU7KcGJI6EgRR673W+EHdocvuTp7/NRDu/2YZTPIsKKoL8sdrYWhLwm76ihftvk7XvDdR4mndN42jTzC2eX5a39Q5u2Mqdr4UKEN680pNsdypqtEtefDpfR/FgrqFMWSSMeOOWZwfcPPMp4yCXxHh62uqGeWgkKMYRTwHJej5t3Ncyfa+SqhQWxasK0HuiZNabtxLZFEt40ZzYPcj9Hrm4jtbZfQQ9dQkXeC57jwghA8IFO2qGkdFzYTQEBPJ0u4JBoOc7zp4tSG/k3+NNpl9IpSAe4KIJmjnA/iXTBOSnvxtIkf8muoTuEmxSpIpG02QugHrsj6VU=
    token: AgCglSPc/yPcPJbh1smPat/BqpBMgBuzq63tQUKTHpyOyOTsG2oFYXfbxFtQIXKRmwpXC7QYfWMPefj9LUr9owrZFFROh8ArvhcHZkJwtAKTdEWZK3pj2gsD6H873XyftsXOJ1ZmyTO34p3tBWTAXC7os/rqREvh9LM4kxYRqKqtJip++WrH6zQNYz74iAEX4yRl3z1B7OtXTGKn9/u46OkillFmrh51CLqCkdVV2r08ATlz1p1hfCN9MUyfKEIfIFXCrybm5B2zHq71CYPm+MTTCkf6blI0qaEq1Jl46HP6c1WqZRKSBZoHt7F0DlWOm9QZU9Gn6zE1xq8EZGp0e3C//v/OYIEDRW64DG+2WYLw+sToaL+Th0oj/OQVQhcaH8T45sgj7OiKrsKLy0AMcscxol+cXvTphM8k21qc4Bwn/3O2YCKKVXpzzVyOvDuxvteqgWRuuIMdI0cPgfMx4khA3JzU7/swpKZm/n5JSvqt+dIZHx6JmNs5XTjTn6JWyENCi81Ou6R4tobSR0IySj+/+cxrajY+S6ryZRSPCDYz/pcEI/HELojQYBm9iy22UhdW4WAq2CJK/Z9tYP37s1EMxYPkGgsjqTx5K0dO0m3YbdABZTbOGEKY4FszQUEuuC1P6NcgFt6r+DP+rpxxNWtw/tIwe0GXlqlN3apz55Fj58C8ayFwfQP/P8jGo41yXPvRe84xyB/mtjt0BhdMsMNJyIZahic8uE7dwctl7IxZ8e5gvZThEKSNQkDDazNoRmtdm4pTuOvp0rE92md/mX2yk6QSmoYUF8duoJCJQU0X9+j+1/wQynrPldrNcmwLjqGeqYNe17tJki6b5R+DOBGSWfqV+3DJFU8Vd4QYT++TBHso6mfluRvbR6ggslU/jnlMtuErdg+9UiKeEuaBBAIWkRGJlVRpPu6w8HkigQ+5KrvSxmZ+OkWvGpqvvRIKyiVbnIfHsomGmEQYr512N2LUxOr9c8+7urR8NjFToSRF8pkYlju8W3bkRRmxIsn4+1uwdxtoAEY0QUEB72dmHyjjho2aXn+aZmOuGzebLfRGIY3j74kMABgYZHb11Utk/+MvfNePAH0NQ0N7bWW51sSk+++yU/L/FksxuMR7tXF0wrbeH6+Dz9UV1A+MyCX6T5nJvDq7fpTy1iOFpdvUa16oOT6OEZVx4IuR+nCWukdCXnYKPWlaJUOFD3H3RrjxCdlogP/Fq4Y7VtwERSE5Stnwa9cDl9qodegxh0wgYw7Zk9p7wgCI+lq/VWL3kwrmdOeH+J4VavVRQfw/w8q4eKrFY/mPuf9mmbLSWFi12OQl9moPPnS5u4v2YparQmjtBfW5XHQvi73VEZGos5h7+cv5NyJ21Kq2A0cmu5YFuxQ6LZJpzQff7PN7Ogc0UJ/OMyax6US6mEcATJeu9iEXi6lp3aM8jVWeMYh3cMf6YUwuWnUT9JH6YvjAYXBXPmrtp5NlA2U5KG2mCme8cPIhkFM5NjnnCJKhJj2sW8OvO6aL5Qn452+97eHDffBrPz0WOEtVL5/occhBeWSzFSjP6JbMZik=
  template:
    metadata:
      name: 1password-connect
      namespace: 1password
    type: Opaque
