apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: aws-controllers
  namespace: flux-system
spec:
  type: oci
  interval: 30m
  url: oci://public.ecr.aws/aws-controllers-k8s
