apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jellyseerr-fallback
  namespace: flux-system
spec:
  type: oci
  interval: 5m
  url: oci://ghcr.io/m0nsterrr/helm-charts
