apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app metube
  labels: &labels
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  replicas: 1
  selector:
    matchLabels:
      <<: *labels
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - rachel
      containers:
        - name: *app
          env:
            - name: DOWNLOAD_DIR
              value: /downloads-1
            - name: OUTPUT_TEMPLATE
              value: "%(playlist_title)s.S00E%(playlist_index)s.%(title)s.%(ext)s"
            - name: OUTPUT_TEMPLATE_PLAYLIST
              value: "%(playlist_title)s.S00E%(playlist_index)s.%(title)s.%(ext)s"
            - name: STATE_DIR
              value: /state
            - name: TEMP_DIR
              value: /downloads-1
            - name: GID
              value: "1000"
            - name: UID
              value: "1000"
            - name: YTDL_OPTIONS
              # language=json
              value: |
                {
                  "cookiefile": "/cookies/cookies.txt",
                  "postprocessors": [
                    {
                      "key": "FFmpegMetadata",
                      "add_metadata": true,
                      "add_chapters":true
                    },
                    {
                      "key":"EmbedThumbnail"
                  }
                  ],
                  "convertthumbnails": "png",
                  "writethumbnail": true
                }
          image: ghcr.io/alexta69/metube:2025-05-30
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8081
              name: http
          volumeMounts:
            - name: cookies
              mountPath: /cookies
            - name: downloads-1
              mountPath: /downloads-1
            - name: state
              mountPath: /state
            - name: temp
              mountPath: /tmp
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsGroup: 1000
        runAsUser: 1000
      tolerations:
        - key: nas
          operator: Equal
          value: "true"
          effect: NoSchedule
      volumes:
        - name: cookies
          secret:
            secretName: metube-patreon-cookies
        - name: downloads-1
          persistentVolumeClaim:
            claimName: metube-downloads-1
        - name: state
          persistentVolumeClaim:
            claimName: metube-state
        - name: temp
          emptyDir: {}
