apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: metube-patreon-cookies
  labels:
    app.kubernetes.io/name: metube
    app.kubernetes.io/instance: metube
spec:
  data:
    - remoteRef:
        key: metube-patreon-cookies
      secretKey: cookies.txt
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: metube-patreon-cookies
