apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metube-state
  labels:
    app.kubernetes.io/name: metube
    app.kubernetes.io/instance: metube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metube-downloads-1
  labels:
    app.kubernetes.io/name: metube
    app.kubernetes.io/instance: metube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3T
  volumeName: metube-downloads-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: metube-downloads-1
  labels:
    app.kubernetes.io/name: metube
    app.kubernetes.io/instance: metube
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 3T
  local:
    path: "/mnt/NAS/metube"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - rachel
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
