apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-ngx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  data:
    - remoteRef:
        key: paperless-ngx
        property: username
      secretKey: PAPERLESS_ADMIN_USER
    - remoteRef:
        key: paperless-ngx
        property: password
      secretKey: PAPERLESS_ADMIN_PASSWORD
    - remoteRef:
        key: paperless-ngx
        property: secret-key
      secretKey: PAPERLESS_SECRET_KEY
    - remoteRef:
        key: paperless-ngx
        property: socialaccount-providers
      secretKey: PAPERLESS_SOCIALACCOUNT_PROVIDERS
    - remoteRef:
        key: paperless-ngx
        property: redis-url
      secretKey: PAPERLESS_REDIS
  target:
    name: paperless-ngx
