apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-consume
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
  volumeName: pvc-e70fd264-f32a-4481-98fa-f6ec865eccd1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
  volumeName: pvc-f50ffab8-b9d6-4cb0-80db-64e760dbb48f

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-media
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeName: pvc-885eeea2-54aa-4f5d-9322-d4d24465c290
