apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: home-infrastructure-commit-status
  namespace: flux-system
spec:
  type: github
  address: https://github.com/denniseffing/home-infrastructure
  secretRef:
    name: github-commit-status
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: home-infrastructure-github-commit-status
  namespace: flux-system
spec:
  providerRef:
    name: home-infrastructure-github-commit-status
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: "*"
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: home-infrastructure-private-github-commit-status
  namespace: flux-system
spec:
  type: github
  address: https://github.com/denniseffing/home-infrastructure-private
  secretRef:
    name: github-commit-status
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: home-infrastructure-private-github-commit-status
  namespace: flux-system
spec:
  providerRef:
    name: home-infrastructure-private-github-commit-status
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: "*"
