apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tv-shows-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Ti
  volumeName: tv-shows-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tv-shows-1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 3Ti
  local:
    path: "/mnt/NAS/TV Shows"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - rachel
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tv-shows-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8.6T
  volumeName: tv-shows-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tv-shows-2
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8.6T
  local:
    path: "/mnt/NAS/TV Shows"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - rachel
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Ti
  volumeName: movies-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies-1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 3Ti
  local:
    path: "/mnt/NAS/Movies"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - rachel
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8.6T
  volumeName: movies-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies-2
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8.6T
  local:
    path: "/mnt/NAS/TV Shows"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - rachel
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Ti
  volumeName: music-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 3Ti
  local:
    path: "/mnt/NAS/Music"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - rachel
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8.6T
  volumeName: music-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-2
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8.6T
  local:
    path: "/mnt/NAS/TV Shows"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - rachel
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
