apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-storage-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Ti
  volumeName: plex-storage-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-storage-1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 3Ti
  local:
    path: "/mnt/storage-1/plex"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - rachel
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-storage-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Ti
  volumeName: plex-storage-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-storage-2
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 12Ti
  local:
    path: "/mnt/storage-2/plex"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - rachel
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
