apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: monitoring
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 66.*
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  values:
    alertmanager:
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        enabled: true
        hosts:
          - alertmanager.internal.denniseffing.de
        tls:
          - hosts:
              - alertmanager.internal.denniseffing.de
            secretName: alertmanager-ingress-tls
    grafana:
      extraSecretMounts:
        - name: grafana-github-auth-secret-mount
          secretName: grafana-github-auth-secret
          defaultMode: 0440
          mountPath: /etc/secrets/auth_github
          readOnly: true
      grafana.ini:
        auth.github:
          enabled: true
          client_id: "$__file{/etc/secrets/auth_github/client_id}"
          client_secret: "$__file{/etc/secrets/auth_github/client_secret}"
          allow_assign_grafana_admin: true
          role_attribute_path: "[login=='denniseffing'][0] && 'GrafanaAdmin'"
          role_attribute_strict: true
        server:
          root_url: "https://%(domain)s"
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        enabled: true
        hosts:
          - grafana.internal.denniseffing.de
        tls:
          - hosts:
              - grafana.internal.denniseffing.de
            secretName: grafana-ingress-tls
    prometheus:
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        enabled: true
        hosts:
          - prometheus.internal.denniseffing.de
        tls:
          - hosts:
              - prometheus.internal.denniseffing.de
            secretName: prometheus-ingress-tls
      prometheusSpec:
        retention: 10d
        retentionSize: 7.5GiB
        serviceMonitorSelectorNilUsesHelmValues: false
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
  install:
    crds: CreateReplace
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: grafana-github-auth-secret
  namespace: monitoring
spec:
  itemPath: "vaults/Home Cluster/items/grafana-github-oauth-app"
