apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  interval: 24h
  releaseName: nginx-ingress-controller
  chart:
    spec:
      chart: ingress-nginx
      version: 4.*
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
  values:
    controller:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      service:
        annotations:
          kube-vip.io/forwardUPNP: true
