---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaServiceAccount
metadata:
  name: grafana-mcp-server
spec:
  instanceName: grafana
  name: grafana-mcp-server
  role: Viewer
  tokens:
    - name: grafana-mcp
      secretName: grafana-mcp-service-account
