apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-oauth-app
  namespace: oauth2-proxy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  data:
    - remoteRef:
        key: oauth2-proxy-oauth-app
        property: client_id
      secretKey: client-id
    - remoteRef:
        key: oauth2-proxy-oauth-app
        property: client_secret
      secretKey: client-secret
    - remoteRef:
        key: oauth2-proxy-oauth-app
        property: cookie_secret
      secretKey: cookie-secret
  target:
    name: oauth2-proxy-oauth-app
