---
- name: Prepare nodes
  hosts: k3s_cluster
  become: true
  vars:
    longhorn_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}"
  tasks:
    - name: Configure DNS server
      community.general.nmcli:
        conn_name: "Wired connection 1"
        type: ethernet
        ifname: eth0
        dns4:
          - 1.1.1.1
        state: present
      notify:
        - Restart NetworkManager
    - name: Enable dm_crypt kernel module
      modprobe:
        name: dm_crypt
        state: present
        persistent: present
    - name: Install packages required by Longhorn
      package:
        name:
          - open-iscsi
          - cryptsetup
        state: present
    - name: Start services required by Longhorn
      service:
        name: iscsid
        enabled: true
        state: started
    - name: Configure IPv6 prerequisites for Matter Controller
      sysctl:
        name: '{{ item.key }}'
        value: '{{ item.value }}'
        reload: true
        state: present
      with_dict:
        net.ipv6.conf.eth0.accept_ra: 1
        net.ipv6.conf.eth0.accept_ra_rt_info_max_plen: 64
  handlers:
    - name: Restart NetworkManager
      ansible.builtin.systemd:
        name: NetworkManager
        state: restarted
- name: Build a cluster with a single control node and Cilium CNI
  hosts: k3s_cluster
  vars:
    k3s_become: true
    k3s_etcd_datastore: true
    k3s_state: installed
    k3s_registration_address: 192.168.178.40
    k3s_server_manifests_templates:
      - manifests/kube-vip.yaml
      - manifests/kube-vip-cloud-controller.yaml
    k3s_server:
      cluster-cidr: 10.52.0.0/16
      flannel-backend: "none"
      disable-network-policy: true
      disable:
        - traefik
        - servicelb
      tls-san: 192.168.178.40
  roles:
    - role: xanmanning.k3s
