apiVersion: v1
kind: Namespace
metadata:
  name: home-assistant
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: pajikos
  namespace: home-assistant
spec:
  interval: 6h
  url: https://pajikos.github.io/home-assistant-helm-chart/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  chart:
    spec:
      chart: home-assistant
      sourceRef:
          kind: HelmRepository
          name: pajikos
      version: 0.2.*
  interval: 5m
  values:
    additionalMounts:
      - mountPath: /var/run/dbus
        name: bluetooth
      - mountPath: /config/gitops
        name: gitops-config
    additionalVolumes:
      - hostPath:
          path: /var/run/dbus
        name: bluetooth
      - configMap:
          name: home-assistant-gitops-config
        name: gitops-config
    addons:
      codeserver:
        enabled: true
        ingress:
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          className: nginx-internal
          enabled: true
          hosts:
            - host: home-config.internal.denniseffing.de
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - home-config.internal.denniseffing.de
              secretName: home-assistant-config-ingress-tls
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - ross
                    - monica
    configuration:
      enabled: true
      forceInit: true
      trusted_proxies:
        - 192.168.178.0/24
      templateConfig: |-
        # Loads default set of integrations. Do not remove.
        default_config:

        {{- if .Values.ingress.enabled }}
        http:
          use_x_forwarded_for: true
          trusted_proxies:
            {{- range .Values.configuration.trusted_proxies }}
            - {{ . }}
            {{- end }}
        {{- end}}
        # Load frontend themes from the themes folder
        frontend:
          themes: !include_dir_merge_named themes

        automation: !include automations.yaml
        script: !include scripts.yaml
        scene: !include scenes.yaml
        group: !include gitops/groups.yaml # matches mount path of gitops-config config map
        
        automation gitops: !include gitops/automations.yaml # matches mount path of gitops-config config map
    dnsPolicy: ClusterFirstWithHostNet
    hostNetwork: true
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      className: nginx-internal
      enabled: true
      hosts:
        - host: home.internal.denniseffing.de
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - home.internal.denniseffing.de
          secretName: home-assistant-ingress-tls
    persistence:
      accessMode: ReadWriteOnce
      enabled: true
      size: 20Gi
      storageClass: longhorn
    securityContext:
      privileged: true
    serviceMonitor:
      enabled: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant-gitops-config
  namespace: home-assistant
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: apps/home-assistant-config
  prune: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matter-server
  namespace: home-assistant
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - ross
                      - monica
      containers:
        - name: matter-server
          image: ghcr.io/home-assistant-libs/python-matter-server:7.0.1
          ports:
            - containerPort: 5580
              name: websocket
          securityContext:
            appArmorProfile:
              type: Unconfined
            privileged: true
          volumeMounts:
            - mountPath: /var/run/dbus
              name: bluetooth
              readOnly: true
            - mountPath: /data
              name: data
      hostNetwork: true
      volumes:
        - name: bluetooth
          hostPath:
            path: /var/run/dbus
        - name: data
          persistentVolumeClaim:
            claimName: matter-server
    metadata:
      labels:
        app.kubernetes.io/name: matter-server
        app.kubernetes.io/instance: matter-server
  selector:
    matchLabels:
      app.kubernetes.io/name: matter-server
      app.kubernetes.io/instance: matter-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matter-server
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: Service
metadata:
  name: matter-server
  namespace: home-assistant
spec:
  type: ClusterIP
  ports:
    - name: websocket
      port: 5580
      targetPort: websocket
  selector:
    app.kubernetes.io/name: matter-server
    app.kubernetes.io/instance: matter-server
