apiVersion: v1
kind: Namespace
metadata:
  name: jdownloader
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jdownloader
  namespace: jdownloader
  labels:
    app.kubernetes.io/name: jdownloader
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jdownloader
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - rachel
      containers:
        - name: jdownloader
          image: jlesage/jdownloader-2
          ports:
            - containerPort: 5800
              name: http
              protocol: TCP
          env:
            - name: USER_ID
              value: "1000"
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /output
              name: output
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jdownloader-config
        - name: output
          hostPath:
            path: /mnt/NAS
  selector:
    matchLabels:
      app.kubernetes.io/name: jdownloader
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jdownloader-config
  namespace: jdownloader
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: Service
metadata:
  name: jdownloader
  namespace: jdownloader
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5800
      targetPort: http
  selector:
    app.kubernetes.io/name: jdownloader
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: jdownloader
  namespace: jdownloader
spec:
  rules:
    - host: jdownloader.internal.denniseffing.de
      http:
        paths:
          - backend:
              service:
                name: jdownloader
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - jdownloader.internal.denniseffing.de
      secretName: jdownloader-ingress-tls
