apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-csi-driver
spec:
  interval: 30m
  releaseName: cert-manager-csi-driver
  chart:
    spec:
      chart: cert-manager-csi-driver
      version: v0.11.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  dependsOn:
    - name: cert-manager
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    metrics:
      podmonitor:
        enabled: true
