apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  data:
    - remoteRef:
        key: radarr
        property: api-key
      secretKey: RADARR__AUTH__APIKEY
  target:
    name: radarr
