apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress-external
  namespace: nginx-ingress
spec:
  interval: 24h
  releaseName: nginx-ingress-controller-external
  chart:
    spec:
      chart: ingress-nginx
      version: 4.*
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
  values:
    controller:
      ingressClassResource:
        controllerValue: k8s.io/ingress-nginx-external
        name: nginx-external
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      service:
        annotations:
          kube-vip.io/forwardUPNP: true
        externalTrafficPolicy: Local
    fullnameOverride: nginx-ingress-controller-external
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress-internal
  namespace: nginx-ingress
spec:
  interval: 24h
  releaseName: nginx-ingress-controller-internal
  chart:
    spec:
      chart: ingress-nginx
      version: 4.*
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
  values:
    controller:
      config:
        whitelist-source-range: 192.168.0.0/16
      ingressClassResource:
        controllerValue: k8s.io/ingress-nginx-internal
        default: true
        name: nginx-internal
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      service:
        annotations:
          kube-vip.io/forwardUPNP: false
        externalTrafficPolicy: Local
      watchIngressWithoutClass: true
    fullnameOverride: nginx-ingress-controller-internal
