name: "Flux Local"

on:
  pull_request:
    branches: ["main"]
    paths:
      - kubernetes/main/apps/**
      - kubernetes/main/infrastructure/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run flux-local test
        uses: docker://ghcr.io/allenporter/flux-local:v7.1.0
        with:
          args: test --enable-helm --all-namespaces --path /github/workspace/kubernetes/main/cluster -v

  diff:
    name: 🆚 Diff
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        resources: ["helmrelease", "kustomization"]
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Checkout Pull Request Branch
        uses: actions/checkout@v4
        with:
          path: pull

      - name: Checkout Default Branch
        uses: actions/checkout@v4
        with:
          ref: "${{ github.event.repository.default_branch }}"
          path: default

      - name: Run flux-local diff
        uses: docker://ghcr.io/allenporter/flux-local:v7.1.0
        with:
          args: >-
            diff ${{ matrix.resources }}
            --unified 6
            --path /github/workspace/pull/kubernetes/main/cluster
            --path-orig /github/workspace/default/kubernetes/main/cluster
            --strip-attrs "helm.sh/chart,checksum/config,app.kubernetes.io/version,chart"
            --limit-bytes 10000
            --all-namespaces
            --sources "flux-system"
            --output-file diff.patch

      - name: Generate Diff
        id: diff
        run: |
          cat diff.patch;
          {
              echo 'diff<<EOF'
              cat diff.patch
              echo EOF
          } >> "$GITHUB_OUTPUT";
          {
              echo "### Diff"
              echo '```diff'
              cat diff.patch
              echo '```'
          } >> "$GITHUB_STEP_SUMMARY"

      - if: ${{ steps.diff.outputs.diff != '' }}
        name: Add Comment
        uses: mshick/add-pr-comment@v2
        with:
          message-id: "${{ github.event.pull_request.number }}/kubernetes/${{ matrix.resources }}"
          message-failure: Diff was not successful
          message: |
            ```diff
            ${{ steps.diff.outputs.diff }}
            ```

  flux-local-success:
    needs: ["test", "diff"]
    if: ${{ always() }}
    name: Successful
    runs-on: ubuntu-latest
    steps:
      - name: Check flux-local status
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
